// Generated by https://quicktype.io

export interface CharacterResponse {
    docs:          Character[];
    totalDocs:     number;
    limit:         number;
    totalPages:    number;
    page:          number;
    pagingCounter: number;
    hasPrevPage:   boolean;
    hasNextPage:   boolean;
    prevPage:      null;
    nextPage:      number;
}

export interface Character {
    _id:        string;
    Nombre:     string;
    Historia:   string;
    Imagen:     string;
    Genero:     string;
    Estado:     string;
    Ocupacion:  string;
    updatedAt?: string;
}
